#Sovellus nimi
spring.application.name=bookstore
#H2 konsolikäyttöön
spring.h2.console.enabled=true
#H2 konsolin osoite
spring.h2.console.path=/h2-console
#H2 ajonakaisen kannan osoite
spring.datasource.url=jdbc:h2:mem:testdb
#Yhteinen polku kaikille Rest rajapinnoille
spring.data.rest.base-path=/api
