#Sovellus nimi
spring.application.name=bookstore
#H2 konsolikäyttöön
#spring.h2.console.enabled=true
#H2 konsolin osoite
#spring.h2.console.path=/h2-console
#H2 ajonakaisen kannan osoite
#spring.datasource.url=jdbc:h2:mem:testdb
#Yhteinen polku kaikille Rest rajapinnoille
spring.data.rest.base-path=/api

spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Paikallinen Win PostgreSQL  
#spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
#spring.datasource.username=postgres
#spring.datasource.password=

#DELL WYSE PostgreSQL. Kommentoi pois, kun ei käytetä
spring.datasource.url=jdbc:postgresql://192.168.32.185:5432/postgres-db
spring.datasource.username=jex
spring.datasource.password=

#JPA/hibernate ei tee muutoksia ulkoiseen kantaan none arvolla
spring.jpa.hibernate.ddl-auto=none
